#!/usr/bin/env bash
#
#
# Feel free to add new aliases or edit the default ones as
# much as you want, but always watch the consequences. It
# is recommended to keep these aliases without modifying it
# since some dotfiles may need them as they are in default
#
# @author losedavidpb

source ~/.config/shell/exports

# Alias for all commands that use the available package manager
case $PACKAGE_MANAGER in
	"yum")
		alias install="sudo yum install"
		alias uninstall="sudo yum remove"
		alias update="sudo yum update"
		alias list_all_packs="yum list"
		alias search_pack="yum list | egrep"
	;;

	"apt")
		alias install="sudo apt install"
		alias uninstall="sudo apt remove"
		alias update="sudo apt update"
		alias list_all_packs="sudo apt list"
		alias search_pack="sudo apt list | egrep"
	;;

	"apt-get")
		alias install="sudo apt-get install"
		alias uninstall="sudo apt-get remove"
		alias update="sudo apt-get update"
		alias list_all_packs="sudo apt-get list"
		alias search_pack="sudo apt list | egrep"
	;;

	# Default value for pacman package manager
	*)
		alias install="sudo pacman -Syyu"
		alias uninstall="sudo pacman -Rns"
		alias update="sudo pacman -Syyu"
		alias list_all_packs="pacman -Q"
		alias search_pack="pacman -Q"
	;;
esac

alias reload_bash="source ~/.bashrc"         # reload bash config
alias reload_zsh="source ~/.zshrc"           # reload zsh config

alias .="cd ../"                             # go back just once
alias ..="cd ../.."                          # go back twice
alias dl="cd ~/Downloads"                    # shortcut to downloads
alias dc="cd  ~/Documents"                   # shortcut to documents

alias ls="ls --color=auto -F"                # show current files with colors
alias lls="ls -l --color=auto -F"            # show detailed current files with colors
alias lsd="ls -lCd .?* --color=auto -F"      # show current dotfiles with colors
alias llsd="ls -ld .?* --color=auto -F"      # show detailed current dotfiles with colors
alias lsa="ls -laC --color=auto -F"          # show all current files with colors
alias llsa="ls -la --color=auto -F"          # show all detailed current files with colors

alias grep='grep --colour=auto'              # find with greep with colors
alias egrep='egrep --colour=auto'            # find with egreep with colors
alias fgrep='fgrep --colour=auto'            # find with fgreep with colors

alias df="df -h"                             # human-readable sizes
alias dfdev="df -Th | grep '^/dev'"          # human-readable sizes for devs
alias free="free -m"                         # show sizes in MB

alias more=less                              # both commands do the same
alias cpi="cp -i"                            # confirm before overwriting something
alias cpr="cp -r"							 # copy files and directories
alias rrm="rm -fR "                          # remove all files inside current directory
alias cls="clear"                            # clear current terminal

# GNU/Linux System information
alias sysinfo="neofetch --source ~/.config/shell/ascii_icon --colors 133 249 255 133 255"
alias cpuinfo="grep 'model name' /proc/cpuinfo | cut -d ":" -f 2 | uniq"
alias osinfo="echo $(uname -o) $(uname -m)"
alias uptime="uptime -p | cut -c 4-"
alias kernelinfo="uname -r"
alias ddate='date +"%R - %a, %B %d, %Y"'
