#!/usr/bin/env bash
#
#
# Feel free to add new aliases or edit the default ones as
# much as you want, but always watch the consequences. It
# is recommended to keep these aliases without modifying it
# since some dotfiles may need them as they are in default
#
# @author losedavidpb

script_path="${BASH_SOURCE:-$0}"
abs_script_path="$(realpath "${script_path}")"
_shell_abs_script_directory="$(dirname "${abs_script_path}")"
unset script_path abs_script_path

source $_shell_abs_script_directory/exports

# Aliases for package manager.
#
# It is important to notice that this aliases
# would be defined as expected whether current
# machine has installed an available one
case $PACKAGE_MANAGER in
	"yum")
		alias install="sudo yum install"
		alias uninstall="sudo yum remove"
		alias update="sudo yum update"
		alias list_all_packs="yum list"
		alias search_pack="yum list | egrep"
	;;

	"pacman")
		alias install="sudo pacman -Syyu"
		alias uninstall="sudo pacman -Rns"
		alias update="sudo pacman -Syyu"
		alias list_all_packs="pacman -Q"
		alias search_pack="pacman -Q | egrep"
	;;

	"emerger")
		alias install="sudo emerge"
		alias uninstall="sudo emerge -C"
		alias update="sudo emerge -uD world"
		alias list_all_packs="emerge -s"
		alias search_pack="emerge -s | egrep"
	;;

	"zypp")
		alias install="sudo zypper ar"
		alias uninstall="sudo zypper rr"
		alias update="sudo zypper refresh"
		alias list_all_packs="zypper repos"
		alias search_pack="zypper repos | egrep"
	;;

	"apt")
		alias install="sudo apt install"
		alias uninstall="sudo apt remove"
		alias update="sudo apt update"
		alias list_all_packs="apt list"
		alias search_pack="apt list | egrep"
	;;

	"apt-get")
		alias install="sudo apt-get install"
		alias uninstall="sudo apt-get remove"
		alias update="sudo apt-get update"
		alias list_all_packs="apt list"
		alias search_pack="apt list | egrep"
	;;

	"apk")
		alias install="sudo apk add"
		alias uninstall="sudo apk del"
		alias update="sudo apk update"
		alias list_all_packs="apk search -v"
		alias search_pack="apk search -v | egrep"
	;;

	*)
		alias install="echo \"error: command not available\""
		alias uninstall="echo \"error: command not available\""
		alias update="echo \"error: command not available\""
		alias list_all_packs="echo \"error: command not available\""
		alias search_pack="echo \"error: command not available\""
	;;
esac

alias .="cd ../"                             # go back just once
alias ..="cd ../.."                          # go back twice
alias dl="cd ~/Downloads"                    # shortcut to downloads
alias dc="cd  ~/Documents"                   # shortcut to documents

alias cwsl="cd $WSL_FS"					     # shortcut to WSL file system
alias cdwslh="cd $WSL_HOME"					 # shortcut to WSL home

alias wsldl="cd $WSL_HOME/Downloads"		 # shortcut to WSL downloads
alias wsldc="cd $WSL_HOME/Documents"		 # shortcut to WSL documens
alias cdapps="cd $WSL_APPS"					 # shortcut to WSL Apps
alias cdulpgc="cd $WSL_APPS"				 # shortcut to WSL ULPGC
alias cdcurrcourse="cd $WSL_APPS"			 # shortcut to WSL current course

alias ls="ls --color=auto -F"                # show current files with colors
alias lls="ls -l --color=auto -F"            # show detailed current files with colors
alias lsd="ls -lCd .?* --color=auto -F"      # show current dotfiles with colors
alias llsd="ls -ld .?* --color=auto -F"      # show detailed current dotfiles with colors
alias lsa="ls -laC --color=auto -F"          # show all current files with colors
alias llsa="ls -la --color=auto -F"          # show all detailed current files with colors

alias grep='grep --colour=auto'              # find with greep with colors
alias egrep='egrep --colour=auto'            # find with egreep with colors
alias fgrep='fgrep --colour=auto'            # find with fgreep with colors

alias df="df -h"                             # human-readable sizes
alias dfdev="df -Th | grep '^/dev'"          # human-readable sizes for devs
alias free="free -m"                         # show sizes in MB

alias more=less                              # both commands do the same
alias cpi="cp -i"                            # confirm before overwriting something
alias cpr="cp -r"							 # copy files and directories
alias rrm="rm -fR "                          # remove all files inside current directory
alias cls="clear"                            # clear current terminal

# GNU/Linux System information
alias sysinfo="neofetch --source ~/.config/neofetch/ascii_icon --colors 133 249 255 133 255 255"
alias cpuinfo="grep 'model name' /proc/cpuinfo | cut -d ":" -f 2 | uniq"
alias osinfo="echo $(uname -o) $(uname -m)"
alias uptime="uptime -p | cut -c 4-"
alias kernelinfo="uname -r"
alias ddate='date +"%R - %a, %B %d, %Y"'