#!/usr/bin/env bash
#
# @author losedavidpb
#

# Append path to global variable PATH with no redundance
# # usage: pathappend <absolute_path>
function pathappend () {
  if [[ $# = 1 ]]; then
    local actpath=$(echo $PATH | cut -d ":" -f 1)
    local condappend=1
    local actpos=1

    # Check if PATH would have redundance whether $1 was included
    while [[ $actpath != "" ]]; do
      if [[ $actpath = $1 ]]; then
          condappend=0
          break
      fi

      actpos=$(($actpos+1))
      actpath=$(echo $PATH | cut -d ":" -f $actpos)
    done

    if [[ $condappend = 1 ]]; then
      export PATH="${PATH:+$PATH:}$1"
    fi
  fi
}

# Configuration for WSL
export DISPLAY=:0

# Terminfo color
export TERM=xterm-256color

# Visual mode for start
export SHELL_STARTUP_MODE=pretty

# Default editor and terminal
export EDITOR=/usr/bin/nano
export TERMINAL=/usr/bin/termite
export SHELL=/bin/bash	# or /bin/zsh
export SHELL_NAME=bash  # or zsh

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8'

# ZSH settings
export ZSH=/usr/share/zsh
export ZSH_PLUGINS=$ZSH/plugins

# Word chars
export WORDCHARS=${WORDCHARS//\/[&.;]}

# History settings
export HISTFILE=~/.config/shell/.bash_history # or ~/.config/shell/.zhistory
export HISTSIZE=1000
export SAVEHIST=1000
export HISTCONTROL=ignoreboth

# WSL configuration
export WSL_FS=/mnt/c/
export WSL_HOME=/mnt/c/Users/$USER/
export WSL_APPS=$WSL_HOME/OneDrive\ -\ Universidad\ de\ Las\ Palmas\ de\ Gran\ Canaria/Apps
export WSL_ULPGC=$WSL_HOME/OneDrive\ -\ Universidad\ de\ Las\ Palmas\ de\ Gran\ Canaria/ULPGC
export WSL_CURR_COURSE=$WSL_HOME/OneDrive\ -\ Universidad\ de\ Las\ Palmas\ de\ Gran\ Canaria/ULPGC/4º\ CURSO

# Configuration for chshell
# DO NOT MODIFY ANY OF THESE VALUES
export shell_dir=bash

# Default directories for variable PATH
pathappend $HOME/.local/bin
pathappend /usr/local/bin
pathappend /usr/bin
pathappend /bin
pathappend /usr/local/sbin
pathappend /usr/bin/site_perl
pathappend /usr/bin/vendor_perl
pathappend /usr/bin/core_perl
pathappend /usr/lib/jvm/default/bin
pathappend $WSL_FS
pathappend $WSL_APPS

# Package manager variables
export PACKAGE_MANAGER="unkown"

# List of available package managers associated
# to release plain-text files
declare -a name_pack_manager=(
  yum pacman emerger
  zypp apt apt-get apk
)

declare -a f_pack_manager=(
  redhat-release arch-release gentoo-release
  SuSE-release lsb-release debian_version alpine-release
)

for (( i=0; i<${#name_pack_manager[@]}; i++)); do
	if [[ -f /etc/${f_pack_manager[i]} ]]; then
		export PACKAGE_MANAGER=${name_pack_manager[i]}
		break
	fi
done

unset name_pack_manager f_pack_manager

# Regular colors
export BLACK="\e[0;30m"
export RED="\e[0;31m"
export GREEN="\e[0;32m"
export YELLOW="\e[0;33m"
export BLUE="\e[0;34m"
export MAGENTA="\e[0;35m"
export CYAN="\e[0;36m"
export WHITE="\e[0;37m"

# Regular Bold
export BOLD_BLACK="\e[1;30m"
export BOLD_RED="\e[1;31m"
export BOLD_GREEN="\e[1;32m"
export BOLD_YELLOW="\e[1;33m"
export BOLD_BLUE="\e[1;34m"
export BOLD_MAGENTA="\e[1;35m"
export BOLD_CYAN="\e[1;36m"
export BOLD_WHITE="\e[1;37m"
export BOLD="\e[1m"

# Regular Underline
export UNDERLINE_BLACK="\e[4;30m"
export UNDERLINE_RED="\e[4;31m"
export UNDERLINE_GREEN="\e[4;32m"
export UNDERLINE_YELLOW="\e[4;33m"
export UNDERLINE_BLUE="\e[4;34m"
export UNDERLINE_MAGENTA="\e[4;35m"
export UNDERLINE_CYAN="\e[4;36m"
export UNDERLINE_WHITE="\e[4;37m"
export UNDERLINE="\e[4m"

# Regular background
export BACKGROUND_BLACK="\e[40m"
export BACKGROUND_RED="\e[41m"
export BACKGROUND_GREEN="\e[42m"
export BACKGROUND_YELLOW="\e[43m"
export BACKGROUND_BLUE="\e[44m"
export BACKGROUND_PURPLE="\e[45m"
export BACKGROUND_CYAN="\e[46m"
export BACKGROUND_WHITE="\e[47m"

# Expand Regular Background Horizontally
export EXPAND_BACKGROUND="\e[K"

# Regular background horizontal
export EXPAND_BACKGROUND_BLACK="\e[40m${EXPAND_BACKGROUND}"
export EXPAND_BACKGROUND_RED="\e[41m${EXPAND_BACKGROUND}"
export EXPAND_BACKGROUND_GREEN="\e[42m${EXPAND_BACKGROUND}"
export EXPAND_BACKGROUND_YELLOW="\e[43m${EXPAND_BACKGROUND}"
export EXPAND_BACKGROUND_BLUE="\e[44m${EXPAND_BACKGROUND}"
export EXPAND_BACKGROUND_PURPLE="\e[45m${EXPAND_BACKGROUND}"
export EXPAND_BACKGROUND_CYAN="\e[46m${EXPAND_BACKGROUND}"
export EXPAND_BACKGROUND_WHITE="\e[47m${EXPAND_BACKGROUND}"

# High Intensity Colors
export HI_BLACK="\e[0;90m"
export HI_RED="\e[0;91m"
export HI_GREEN="\e[0;92m"
export HI_YELLOW="\e[0;93m"
export HI_BLUE="\e[0;94m"
export HI_MAGENTA="\e[0;95m"
export HI_CYAN="\e[0;96m"
export HI_WHITE="\e[0;97m"

# Bold High Intensity
export BOLD_HI_BLACK="\e[1;90m"
export BOLD_HI_RED="\e[1;91m"
export BOLD_HI_GREEN="\e[1;92m"
export BOLD_HI_YELLOW="\e[1;93m"
export BOLD_HI_BLUE="\e[1;94m"
export BOLD_HI_MAGENTA="\e[1;95m"
export BOLD_HI_CYAN="\e[1;96m"
export BOLD_HI_WHITE="\e[1;97m"

# High Intensity Background
export HI_BACKGROUND_BLACK="\e[100m"
export HI_BACKGROUND_RED="\e[101m"
export HI_BACKGROUND_GREEN="\e[102m"
export HI_BACKGROUND_YELLOW="\e[103m"
export HI_BACKGROUND_BLUE="\e[104m"
export HI_BACKGROUND_PURPLE="\e[105m"
export HI_BACKGROUND_CYAN="\e[106m"
export HI_BACKGROUND_WHITE="\e[107m"

# Regular background horizontal
export EXPAND_HI_BACKGROUND_BLACK="\e[100m${EXPAND_BACKGROUND}"
export EXPAND_HI_BACKGROUND_RED="\e[101m${EXPAND_BACKGROUND}"
export EXPAND_HI_BACKGROUND_GREEN="\e[102m${EXPAND_BACKGROUND}"
export EXPAND_HI_BACKGROUND_YELLOW="\e[103m${EXPAND_BACKGROUND}"
export EXPAND_HI_BACKGROUND_BLUE="\e[104m${EXPAND_BACKGROUND}"
export EXPAND_HI_BACKGROUND_PURPLE="\e[105m${EXPAND_BACKGROUND}"
export EXPAND_HI_BACKGROUND_CYAN="\e[106m${EXPAND_BACKGROUND}"
export EXPAND_HI_BACKGROUND_WHITE="\e[107m${EXPAND_BACKGROUND}"

# Close Color
export CLOSE_COLOR="\e[0m"

# Color man pages
export LESS_TERMCAP_mb=$'\E[01;32m'
export LESS_TERMCAP_md=$'\E[01;32m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;47;34m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;36m'
export LESS=-r