#!/usr/bin/env bash
#
# @author losedavidpb
#

# Append path to global variable PATH with no redundance
# # usage: pathappend <absolute_path>
function pathappend () {
  if [[ $# = 1 ]]; then
    local actpath=$(echo $PATH | cut -d ":" -f 1)
    local condappend=1
    local actpos=1

    # Check if PATH would have redundance whether $1 was included
    while [[ $actpath != "" ]]; do
      if [[ $actpath = $1 ]]; then
          condappend=0
          break
      fi

      actpos=$(($actpos+1))
      actpath=$(echo $PATH | cut -d ":" -f $actpos)
    done

    if [[ $condappend = 1 ]]; then
      export PATH="${PATH:+$PATH:}$1"
    fi
  fi
}

# Terminfo color
export TERM=xterm-256color

# Visual mode for start
export SHELL_STARTUP_MODE=pretty

# Default editor and terminal
export EDITOR=/usr/bin/nano
export TERMINAL=/usr/bin/termite
export SHELL=/bin/bash	# or /bin/zsh
export SHELL_NAME=bash  # or zsh

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8'

# ZSH settings
export ZSH=/usr/share/zsh
export ZSH_PLUGINS=$ZSH/plugins

# Word chars
export WORDCHARS=${WORDCHARS//\/[&.;]}

# History settings
export HISTFILE=~/.config/shell/.bash_history # or ~/.config/shell/.zhistory
export HISTSIZE=1000
export SAVEHIST=1000
export HISTCONTROL=ignoreboth

# WSL configuration
export WSL_FS=/mnt/c/
export WSL_HOME=/mnt/c/Users/$USER/
export WSL_APPS=$WSL_HOME/OneDrive\ -\ Universidad\ de\ Las\ Palmas\ de\ Gran\ Canaria/Apps
export WSL_ULPGC=$WSL_HOME/OneDrive\ -\ Universidad\ de\ Las\ Palmas\ de\ Gran\ Canaria/ULPGC
export WSL_CURR_COURSE=$WSL_HOME/OneDrive\ -\ Universidad\ de\ Las\ Palmas\ de\ Gran\ Canaria/ULPGC/4º\ CURSO

# Default directories for variable PATH
pathappend $HOME/.local/bin
pathappend /usr/local/bin
pathappend /usr/bin
pathappend /bin
pathappend /usr/local/sbin
pathappend /usr/bin/site_perl
pathappend /usr/bin/vendor_perl
pathappend /usr/bin/core_perl
pathappend /usr/lib/jvm/default/bin
pathappend $WSL_FS
pathappend $WSL_APPS

# Package manager variables
export PACKAGE_MANAGER="unkown"

declare -a pack_manager=(yum pacman apt apt-get)
declare -a file_path=(redhat-release arch-release lsb-release lsb-release)

for (( i=0; i<${#file_path[@]}; i++ )); do
	if [[ -f /etc/${file_path[$i]} ]]; then
		export PACKAGE_MANAGER=${pack_manager[$i]}
		break
	fi
done

unset file_path pack_manager

# End current prompt color
export ENDCOLOR="\[\e[0m\]"

# Regular colors
export BLACK="\[\033[0;30m\]"
export RED="\[\033[0;31m\]"
export GREEN="\[\033[0;32m\]"
export YELLOW="\[\033[0;33m\]"
export BLUE="\[\033[0;34m\]"
export MAGENTA="\[\033[0;35m\]"
export CYAN="\[\033[0;36m\]"
export WHITE="\[\033[0;37m\]"

# Emphasized (bolded) colors
export EMBLACK="\[\033[1;30m\]"
export EMRED="\[\033[1;31m\]"
export EMGREEN="\[\033[1;32m\]"
export EMYELLOW="\[\033[1;33m\]"
export EMBLUE="\[\033[1;34m\]"
export EMMAGENTA="\[\033[1;35m\]"
export EMCYAN="\[\033[1;36m\]"
export EMWHITE="\[\033[1;37m\]"

# Colors with darker values
export DARKBLACK="\[\033[2;30m\]"
export DARKRED="\[\033[2;31m\]"
export DARKGREEN="\[\033[2;32m\]"
export DARKYELLOW="\[\033[2;33m\]"
export DARKBLUE="\[\033[2;34m\]"
export DARKMAGENTA="\[\033[2;35m\]"
export DARKCYAN="\[\033[2;36m\]"
export DARKWHITE="\[\033[2;37m\]"

# Italic colors
export IBLACK="\[\033[3;30m\]"
export IRED="\[\033[3;31m\]"
export IGREEN="\[\033[3;32m\]"
export IYELLOW="\[\033[3;33m\]"
export IBLUE="\[\033[3;34m\]"
export IMAGENTA="\[\033[3;35m\]"
export ICYAN="\[\033[3;36m\]"
export IWHITE="\[\033[3;37m\]"

# Underlined regular colors
export UNBLACK="\[\033[4;30m\]"
export UNRED="\[\033[4;31m\]"
export UNGREEN="\[\033[4;32m\]"
export UNYELLOW="\[\033[4;33m\]"
export UNBLUE="\[\033[4;34m\]"
export UNMAGENTA="\[\033[4;35m\]"
export UNCYAN="\[\033[4;36m\]"
export UNWHITE="\[\033[4;37m\]"

# Background colors
export BGBLACK="\[\033[40m\]"
export BGRED="\[\033[41m\]"
export BGGREEN="\[\033[42m\]"
export BGYELLOW="\[\033[43m\]"
export BGBLUE="\[\033[44m\]"
export BGMAGENTA="\[\033[45m\]"
export BGCYAN="\[\033[46m\]"
export BGWHITE="\[\033[47m\]"

# Color man pages
export LESS_TERMCAP_mb=$'\E[01;32m'
export LESS_TERMCAP_md=$'\E[01;32m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;47;34m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;36m'
export LESS=-r